### ISSUE TITLE
profile.js is loaded in clansample.html

### ISSUE THREAD

**Issue by MarcPlaying** [osuAtoka/hanayo#1]
throwing
![image](https://user-images.githubusercontent.com/35847627/56094185-9c999f00-5ed1-11e9-86f8-d839e7aed22e.png)
at /static/profile.js in line 6

**Comment by Nightsh0t** [comment]
Could you please tell me what page on our website this occurs on?

**Comment by Nightsh0t** [comment]
This has just been fixed. Thank you for notifying us about it.
